version: "3.9"

services:

    nginx:
        container_name: nginx
        build: ./requirements/nginx
        ports:
            - 443:443
            - 80:80
        volumes:
            - type: volume
              source: wp_volume
              target: /wp_volume_target
        restart: always

    wordpress-php:
        container_name: wp_php
        build: ./requirements/wordpress
        volumes:
            - type: volume
              source: wp_volume
              target: /wp_volume_target
        restart: always

volumes:
    wp_volume:
