version: "3.9"

services:

    nginx:
        container_name: nginx
        build: ./requirements/nginx
        ports:
            - 443:443
            - 80:80
        volumes:
            - wp_volume:/shared_data
        restart: always

    wordpress-php:
        container_name: wp_php
        build: ./requirements/wordpress
        volumes:
            - wp_volume:/shared_data
        restart: always

volumes:
    wp_volume:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: ./wp_volume
